cz = {
    "Praha",
    "Brno",
    "Ostrava",
    "Plzen",
    "Liberec",
    "Olomouc",
    "Ceske Budejovice",
    "Usti nad Labem",
    "Hradec Kralove",
    "Pardubice",
    "Zlin",
    "Havirov",
    "Kladno",
    "Most",
    "Opava",
    "Frydek-Mistek",
    "Karvina",
    "Jihlava",
    "Teplice",
    "Decin",
    "Chomutov",
    "Karlovy Vary",
    "Jablonec nad Nisou",
    "Mlada Boleslav",
    "Prostejov",
    "Prerov",
    "Ceska Lipa",
    "Trebic",
    "Trinec",
    "Tabor",
    "Znojmo",
    "Pribram",
    "Cheb",
    "Kolin",
    "Trutnov",
    "Pisek",
    "Orlova",
    "Kromeriz",
    "Vsetin",
    "Sumperk",
    "Uherske Hradiste",
    "Breclav",
    "Hodonin",
    "Cesky Tesin",
    "Litomerice",
    "Litvinov",
    "Novy Jicin",
    "Krnov",
    "Havlickuv Brod",
    "Sokolov",
    "Chrudim",
    "Strakonice",
    "Klatovy",
    "Valasske Mezirici",
    "Koprivnice",
    "Jindrichuv Hradec",
    "Vyskov",
    "Zdar nad Sazavou",
    "Bohumin",
    "Kutna Hora",
    "Blansko",
    "Nachod",
    "Beroun",
    "Melnik",
    "Jirkov",
    "Brandys nad Labem-Stara Boleslav",
    "Zatec",
    "Louny",
    "Kadan",
    "Kralupy nad Vltavou",
    "Hranice",
    "Otrokovice",
    "Bilina",
    "Svitavy",
    "Ostrov",
    "Benesov",
    "Jicin",
    "Uhersky Brod",
    "Roznov pod Radhostem",
    "Bruntal",
    "Neratovice",
    "Pelhrimov",
    "Rakovnik",
    "Slany",
    "Ricany",
    "Dvur Kralove nad Labem",
    "Ceska Trebova",
    "Varnsdorf",
    "Nymburk",
    "Klasterec nad Ohri",
    "Turnov",
    "Usti nad Orlici",
    "Rokycany",
    "Podebrady",
    "Hlucin",
    "Zabreh",
    "Sternberk",
    "Chodov",
    "As",
    "Cesky Krumlov",
    "Roudnice nad Labem",
    "Tachov",
    "Marianske Lazne",
    "Krupka",
    "Vrchlabi",
    "Jaromer",
    "Vysoke Myto",
    "Celakovice",
    "Milovice",
    "Novy Bor",
    "Boskovice",
    "Holesov",
    "Vlasim",
    "Velke Mezirici",
    "Unicov",
    "Kyjov",
    "Jesenik",
    "Domazlice",
    "Susice",
    "Rumburk",
    "Veseli nad Moravou",
    "Rychnov nad Kneznou",
    "Kurim",
    "Humpolec",
    "Prachatice",
    "Frenstat pod Radhostem",
    "Litomysl",
    "Caslav",
    "Nove Mesto na Morave",
    "Moravska Trebova",
    "Lanskroun",
    "Frydlant nad Ostravici",
    "Litovel",
    "Ivancice",
    "Lysa nad Labem",
    "Hlinsko",
    "Prelouc",
    "Studenka",
    "Jesenice",
    "Nove Mesto nad Metuji",
    "Kraluv Dvur",
    "Tisnov",
    "Chotebor",
    "Mohelnice",
    "Nova Paka",
    "Dobris",
    "Lovosice",
    "Policka",
    "Mnichovo Hradiste",
    "Steti",
    "Chocen",
    "Horice",
    "Hostivice",
    "Roztoky",
    "Duchcov",
    "Pribor",
    "Semily",
    "Cerveny Kostelec",
    "Milevsko",
    "Trebon",
    "Rymarov",
    "Bystrice pod Hostynem",
    "Bystrice nad Pernstejnem",
    "Lipnik nad Becvou",
    "Tyn nad Vltavou",
    "Dubi",
    "Nejdek",
    "Hradek nad Nisou",
    "Stribro",
    "Slapanice",
    "Frydlant",
    "Rychvald",
    "Broumov",
    "Bilovec",
    "Benatky nad Jizerou",
    "Vimperk",
    "Moravske Budejovice",
    "Mikulov",
    "Dacice",
    "Vratimov",
    "Sezimovo Usti",
    "Odry",
    "Napajedla",
    "Petrvald",
    "Cernosice",
    "Kaplice",
    "Prestice",
    "Sedlcany",
    "Cesky Brod",
    "Novy Bydzov",
    "Nyrany",
    "Sobeslav",
    "Vodnany",
    "Horovice",
    "Hulin",
    "Kraslice",
    "Letovice",
    "Uvaly",
    "Dobruska",
    "Kravare",
    "Slavkov u Brna",
    "Stare Mesto",
    "Blatna",
    "Holice",
    "Svetla nad Sazavou",
    "Bucovice",
    "Slavicin",
    "Mimon",
    "Letohrad",
    "Senov",
    "Podborany",
    "Veseli nad Luznici",
    "Dubnany",
    "Chrastava",
    "Tanvald",
    "Rosice",
    "Kostelec nad Orlici",
    "Dobrany",
    "Hronov",
    "Zamberk",
    "Kojetin",
    "Zelezny Brod",
    "Tyniste nad Orlici",
    "Odolena Voda",
    "Hustopece",
    "Mnisek pod Brdy",
    "Trest",
    "Trebechovice pod Orebem",
    "Moravsky Krumlov",
    "Vitkov",
    "Tynec nad Sazavou",
    "Rousinov",
    "Upice",
    "Fulnek",
    "Sluknov",
    "Kunovice",
    "Straznice",
    "Jablunkov",
    "Lomnice nad Popelkou",
    "Zubri",
    "Brumov-Bylnice",
    "Nove Straseci",
    "Frantiskovy Lazne",
    "Hradec nad Moravici",
    "Chlumec nad Cidlinou",
    "Stochov",
    "Horni Slavkov",
    "Plana",
    "Hluboka nad Vltavou",
    "Petrovice u Karvine",
    "Jilemnice",
    "Bystrice",
    "Horazdovice",
    "Modrice",
    "Telc",
    "Dolni Lutyne",
    "Ceska Kamenice",
    "Doksy",
    "Velka Bites",
    "Holysov",
    "Kdyne",
    "Bakov nad Jizerou",
    "Trhove Sviny",
    "Jilove",
    "Polna",
    "Rudna",
    "Stary Plzenec",
    "Bechyne",
    "Kosmonosy",
    "Ceska Skalice",
    "Ledec nad Sazavou",
    "Pohorelice",
    "Skutec",
    "Luhacovice",
    "Vrbno pod Pradedem",
    "Tremosna",
    "Horsovsky Tyn",
    "Valasske Klobouky",
    "Nyrsko",
    "Ludgerovice",
    "Chropyne",
    "Namest nad Oslavou",
    "Habartov",
    "Hermanuv Mestec",
    "Protivin",
    "Mezibori",
    "Vizovice",
    "Kynsperk nad Ohri",
    "Bela pod Bezdezem",
    "Unhost",
    "Jilove u Prahy",
    "Pecky",
    "Pacov",
    "Osek",
    "Zruc nad Sazavou",
    "Postoloprty",
    "Oslavany",
    "Votice",
    "Kamenice",
    "Vracov",
    "Vamberk",
    "Adamov",
    "Terlicko",
    "Vendryne",
    "Cvikov",
    "Bolatice",
    "Klimkovice",
    "Bystrice",
    "Horni Sucha",
    "Lisov",
    "Bojkovice",
    "Chlumec",
    "Rozmital pod Tremsinem",
    "Hostinne",
    "Bzenec",
    "Hluk",
    "Bor",
    "Horomerice",
    "Kostelec nad Labem",
    "Uhersky Ostroh",
    "Vejprnice",
    "Detmarovice",
    "Hlubocky",
    "Horni Briza",
    "Kraliky",
    "Slatinany",
    "Zdice",
    "Borovany",
    "Jaromerice nad Rokytnou",
    "Nova Role",
    "Blovice",
    "Plana nad Luznici",
    "Dolni Brezany",
    "Police nad Metuji",
    "Dolni Benesov",
    "Ratiskovice",
    "Brusperk",
    "Pribyslav",
    "Jemnice",
    "Straz pod Ralskem",
    "Psary",
    "Sezemice",
    "Kamenicky Senov",
    "Velke Bilovice",
    "Velesin",
    "Baska",
    "Paskov",
    "Vetrni",
    "Navsi",
    "Mnichovice",
    "Rajhrad",
    "Albrechtice",
    "Sestajovice",
    "Zidlochovice",
    "Mosty u Jablunkova",
    "Zlate Hory",
    "Zbysov",
    "Volary",
    "Kamenice nad Lipou",
    "Brtnice",
    "Smrzovka",
    "Rajec-Jestrebi",
    "Lanzhot",
    "Nepomuk",
    "Kostelec nad Cernymi lesy",
    "Bilovice nad Svitavou",
    "Sazava",
    "Benesov nad Ploucnici",
    "Touzim",
    "Lom",
    "Frystak",
    "Velke Opatovice",
    "Dobrichovice",
    "Nove Mesto pod Smrkem",
    "Lazne Belohrad",
    "Zdiby",
    "Mutenice",
    "Jirikov",
    "Novy Malin",
    "Jablonne v Podjestedi",
    "Klecany",
    "Stod",
    "Zliv",
    "Hrusovany u Brna",
    "Valtice",
    "Svatoborice-Mistrin",
    "Mesto Albrechtice",
    "Lazne Bohdanec",
    "Breznice",
    "Suchdol nad Luznici",
    "Ceske Velenice",
    "Rohatec",
    "Stepanov",
    "Kralovice",
    "Revnice",
    "Libochovice",
    "Ostrozska Nova Ves",
    "Strani",
    "Bustehrad",
    "Krasna Lipa",
    "Velke Prilepy",
    "Stramberk",
    "Nehvizdy",
    "Dobrovice",
    "Chyne",
    "Velka Bystrice",
    "Libcice nad Vltavou",
    "Nivnice",
    "Palkovice",
    "Ujezd u Brna",
    "Libusin",
    "Trmice",
    "Hrusovany nad Jevisovkou",
    "Stankov",
    "Koberice",
    "Libina",
    "Zruc-Senec",
    "Nova Bystrice",
    "Lutin",
    "Tlucna",
    "Haj ve Slezsku",
    "Veverska Bityska",
    "Rapotin",
    "Sadska",
    "Stepankovice",
    "Zelenec",
    "Jablonne nad Orlici",
    "Hanusovice",
    "Kostany",
    "Dobra",
    "Opocno",
    "Zacler",
    "Bridlicna",
    "Uhlirske Janovice",
    "Velke Pavlovice",
    "Zdirec nad Doubravou",
    "Chrast",
    "Desna",
    "Kaznejov",
    "Moravany",
    "Bludov",
    "Tremosnice",
    "Loket",
    "Zasova",
    "Velvary",
    "Kozlovice",
    "Postrelmov",
    "Strelice",
    "Volyne",
    "Cervena Voda",
    "Vnorovy",
    "Vlcnov",
    "Podivin",
    "Rotava",
    "Rtyne v Podkrkonosi",
    "Dolni Bojanovice",
    "Slusovice",
    "Lostice",
    "Chvaletice",
    "Dolni Nemci",
    "Moravsky Beroun",
    "Vrdy",
    "Kostelec na Hane",
    "Vresina",
    "Tepla",
    "Miroslav",
    "Hodkovice nad Mohelkou",
    "Ivanovice na Hane",
    "Luzice",
    "Terezin",
    "Morkovice-Slizany",
    "Velky Tynec",
    "Zirovnice",
    "Budisov nad Budisovkou",
    "Kremze",
    "Ustek",
    "Luka nad Jihlavou",
    "Smirice",
    "Velka nad Velickou",
    "Velke Popovice",
    "Chotesov",
    "Libeznice",
    "Mestec Kralove",
    "Vejprty",
    "Stary Jicin",
    "Cercany",
    "Jirny",
    "Sedlec-Prcice",
    "Pruhonice",
    "Raspenava",
    "Zakupy",
    "Jevicko",
    "Hradek",
    "Spalene Porici",
    "Jedovnice",
    "Celadna",
    "Stara Ves nad Ondrejnici",
    "Kunstat",
    "Konice",
    "Dolany",
    "Mokra-Horakov",
    "Javornik",
    "Dolni Bousov",
    "Korycany",
    "Cesky Dub",
    "Rychnov u Jablonce nad Nisou",
    "Orechov",
    "Stahlavy",
    "Brezova",
    "Hejnice",
    "Plasy",
    "Line",
    "Mlada Vozice",
    "Bast",
    "Kelc",
    "Probostov",
    "Trojanovice",
    "Vestec",
    "Dobra Voda u Ceskych Budejovic",
    "Golcuv Jenikov",
    "Suchdol nad Odrou",
    "Srubec",
    "Velke Hamry",
    "Rokytnice nad Jizerou",
    "Neveklov",
    "Novy Hrozenkov",
    "Vyssi Brod",
    "Velke Losiny",
    "Tuchlovice",
    "Vrane nad Vltavou",
    "Nove Sedlo",
    "Moravska Nova Ves",
    "Netolice",
    "Opatovice nad Labem",
    "Mukarov",
    "Dolni Dobrouc",
    "Luze",
    "Strasice",
    "Zastavka",
    "Pocatky",
    "Rudolfov",
    "Ruda nad Moravou",
    "Bohunovice",
    "Karolinka",
    "Litvinovice",
    "Mikulovice",
    "Nove Hrady",
    "Chabarovice",
    "Morkov",
    "Hat",
    "Jachymov",
    "Bohusovice nad Ohri",
    "Zbuch",
    "Zbiroh",
    "Horka nad Moravou",
    "Zdanice",
    "Chynov",
    "Ledenice",
    "Strancice",
    "Tovacov",
    "Horni Becva",
    "Tlumacov",
    "Hovorcovice",
    "Dolni Kounice",
    "Klobouky u Brna",
    "Cejkovice",
    "Dobsice",
    "Frycovice",
    "Mezimesti",
    "Ostravice",
    "Komarov",
    "Buchlovice",
    "Halenkov",
    "Ceska Ves",
    "Horni Bludovice",
    "Hovezi",
    "Kamenny Ujezd",
    "Cernilov",
    "Velky Osek",
    "Slavonice",
    "Velke Karlovice",
    "Chlumcany",
    "Tisice",
    "Drnovice",
    "Kuncice pod Ondrejnikem",
    "Vranovice",
    "Sobotka",
    "Straz nad Nisou",
    "Krmelin",
    "Batelov",
    "Velke Porici",
    "Vikyrovice",
    "Sokolnice",
    "Kryry",
    "Troubsko",
    "Velka Hledsebe",
    "Nechanice",
    "Mlade Buky",
    "Belkovice-Lastany",
    "Zlutice",
    "Plumlov",
    "Dasice",
    "Lednice",
    "Studena",
    "Brasy",
    "Jince",
    "Peruc",
    "Pozorice",
    "Velke Brezno",
    "Vsetaty",
    "Janovice nad Uhlavou",
    "Mirosov",
    "Nova Vcelnice",
    "Horni Benesov",
    "Valasska Bystrice",
    "Zlonice",
    "Blucina",
    "Horni Jiretin",
    "Nucice",
    "Prusanky",
    "Huslenky",
    "Velim",
    "Hostalkova",
    "Kvasice",
    "Libis",
    "Lustenice",
    "Kardasova Recice",
    "Povrly",
    "Vacenovice",
    "Lany",
    "Stitna nad Vlari-Popov",
    "Sardice",
    "Cerna Hora",
    "Mikulasovice",
    "Solnice",
    "Staric",
    "Mesto Touskov",
    "Hradistko",
    "Zebrak",
    "Rakvice",
    "Rudnik",
    "Budyne nad Ohri",
    "Lipova-lazne",
    "Milin",
    "Hovorany",
    "Borsice",
    "Vcelna",
    "Novosedlice",
    "Luby",
    "Veltrusy",
    "Obrnice",
    "Hranice",
    "Zdounky",
    "Knezmost",
    "Banov",
    "Ralsko",
    "Pist",
    "Vinarice",
    "Moravsky Pisek",
    "Stenovice",
    "Horni Plana",
    "Tvrdonice",
    "Prosec",
    "Stara Paka",
    "Kopidlno",
    "Borohradek",
    "Nydek",
    "Senov u Noveho Jicina",
    "Lhenice",
    "Ricany",
    "Stezery",
    "Hrebec",
    "Nelahozeves",
    "Kobyli",
    "Velka Polom",
    "Tynec nad Labem",
    "Hukvaldy",
    "Svoboda nad Upou",
    "Horni Jeleni",
    "Okrisky",
    "Nizbor",
    "Namest na Hane",
    "Troubky",
    "Hroznetin",
    "Novy Knin",
    "Lesna",
    "Dolni Roven",
    "Markvartovice",
    "Sitborice",
    "Slavkov",
    "Jablunka",
    "Blatnice pod Svatym Antoninkem",
    "Rokytnice v Orlickych horach",
    "Hrochuv Tynec",
    "Stity",
    "Hutisko-Solanec",
    "Polesovice",
    "Sviadnov",
    "Jistebnice",
    "Verovice",
    "Lodenice",
    "Stechovice",
    "Dalovice",
    "Skalna",
    "Nemcice nad Hanou",
    "Hrob",
    "Vaclavovice",
    "Krhova",
    "Merin",
    "Jesenik nad Odrou",
    "Pencin",
    "Velky Senov",
    "Trebenice",
    "Holubice",
    "Bochov",
    "Pysely",
    "Sulice",
    "Dlouha Loucka",
    "Zasmuky",
    "Smecno",
    "Brodek u Prerova",
    "Chlum u Trebone",
    "Kamenice",
    "Mikulcice",
    "Jinocany",
    "Brandysek",
    "Mesice",
    "Stoky",
    "Dolni Ujezd",
    "Krenovice",
    "Plesna",
    "Halenkovice",
    "Pchery",
    "Ceske Mezirici",
    "Studenec",
    "Borsov nad Vltavou",
    "Bilovice",
    "Rudoltice",
    "Lysice",
    "Dolni Becva",
    "Kozmice",
    "Chrast",
    "Predmerice nad Labem",
    "Zvole",
    "Horni Branna",
    "Stare Hradiste",
    "Janovice",
    "Luzna",
    "Bystrany",
    "Kostice",
    "Zandov",
    "Troubelice",
    "Milotice",
    "Kourim",
    "Planany",
    "Raskovice",
    "Hradek",
    "Menin",
    "Hyskov",
    "Dobronin",
    "Moravany",
    "Ratibor",
    "Kunin",
    "Zelechovice nad Drevnici",
    "Lelekovice",
    "Lucany nad Nisou",
    "Kostomlaty nad Labem",
    "Pisek",
    "Krizanov",
    "Dysina",
    "Chodova Plana",
    "Stonava",
    "Vroutek",
    "Velke Hostice",
    "Belotin",
    "Repiste",
    "Svitavka",
    "Drasov",
    "Libouchec",
    "Hnevotin",
    "Radnice",
    "Babice",
    "Chynava",
    "Malsice",
    "Horni Cerekev",
    "Syrovice",
    "Bohutin",
    "Kajov",
    "Cebin",
    "Hodonice",
    "Cervene Pecky",
    "Lidecko",
    "Drnholec",
    "Lanov",
    "Petrvald",
    "Jalubi",
    "Ticha",
    "Pustimer",
    "Skvorec",
    "Senice na Hane",
    "Hermanova Hut",
    "Doudleby nad Orlici",
    "Msene-lazne",
    "Bela pod Pradedem",
    "Velka Dobra",
    "Bohuslavice",
    "Nupaky",
    "Lomnice nad Luznici",
    "Zelesice",
    "Chotoviny",
    "Olsany u Prostejova",
    "Velke Nemcice",
    "Hustopece nad Becvou",
    "Hostomice",
    "Vsestary",
    "Liban",
    "Ostopovice",
    "Libchavy",
    "Lukov",
    "Metylovice",
    "Mirova pod Kozakovem",
    "Hrotovice",
    "Zdikov",
    "Hostka",
    "Policna",
    "Vidce",
    "Krelov-Bruchotin",
    "Bela nad Radbuzou",
    "Prostredni Becva",
    "Hodslavice",
    "Dolni Bukovsko",
    "Divisov",
    "Prezletice",
    "Cernovice",
    "Dolni Poustevna",
    "Zizelice",
    "Sloupnice",
    "Stare Mesto",
    "Kamenne Zehrovice",
    "Ondrejov",
    "Duba",
    "Vrbatky",
    "Sec",
    "Jesenice",
    "Libhost",
    "Vlachovo Brezi",
    "Dolni Dunajovice",
    "Bartosovice",
    "Cerhenice",
    "Davle",
    "Hradec nad Svitavou",
    "Kralice na Hane",
    "Driten",
    "Ronov nad Doubravou",
    "Castolovice",
    "Drahanovice",
    "Brezolupy",
    "Spytihnev",
    "Nasavrky",
    "Horni Mostenice",
    "Svihov",
    "Olovi",
    "Olesnice",
    "Starec",
    "Sedliste",
    "Trsice",
    "Svatava",
    "Zlechov",
    "Doksy",
    "Sumice",
    "Kvetnice",
    "Vysoka nad Labem",
    "Vsenory",
    "Srch",
    "Sumvald",
    "Brezova nad Svitavou",
    "Planice",
    "Kostalov",
    "Brezi",
    "Jablonec nad Jizerou",
    "Vresina",
    "Ropice",
    "Topolna",
    "Dub nad Moravou",
    "Zabcice",
    "Stary Kolin",
    "Zelezna Ruda",
    "Chvalcov",
    "Rozdalovice",
    "Velke Heraltice",
    "Teplice nad Metuji",
    "Smrzice",
    "Ckyne",
    "Kladruby",
    "Slatinice",
    "Mirovice",
    "Telnice",
    "Loucovice",
    "Velemin",
    "Popuvky",
    "Hrusky",
    "Borek",
    "Nedakonice",
    "Jistebnik",
    "Otnice",
    "Primda",
    "Kunice",
    "Homole",
    "Hamry nad Sazavou",
    "Krucemburk",
    "Medlov",
    "Silherovice",
    "Dubne",
    "Pobezovice",
    "Lichnov",
    "Bavorov",
    "Mnisek",
    "Mostkovice",
    "Sedlnice",
    "Hrdejovice",
    "Lety",
    "Novy Saldorf-Sedlesovice",
    "Francova Lhota",
    "Loucna nad Desnou",
    "Poricany",
    "Byst",
    "Kvasiny",
    "Bozice",
    "Kly",
    "Hosteradice",
    "Hazlov",
    "Bystre",
    "Myto",
    "Zitenice",
    "Blizejov",
    "Smidary",
    "Grygov",
    "Libesice",
    "Velen",
    "Bukovany",
    "Rokytnice",
    "Sporice",
    "Zeletava",
    "Brodek u Prostejova",
    "Skalice u Ceske Lipy",
    "Naklo",
    "Tuchomerice",
    "Statenice",
    "Sanov",
    "Rajhradice",
    "Liptal",
    "Male Svatonovice",
    "Dolni Berkovice",
}

sk = {
    "Bratislava",
    "Kosice",
    "Presov",
    "Zilina",
    "Nitra",
    "Banska Bystrica",
    "Trnava",
    "Martin",
    "Trencin",
    "Poprad",
    "Prievidza",
    "Zvolen",
    "Nove Zamky",
    "Povazska Bystrica",
    "Michalovce",
    "Spisska Nova Ves",
    "Komarno",
    "Levice",
    "Humenne",
    "Bardejov",
    "Liptovsky Mikulas",
    "Piestany",
    "Ruzomberok",
    "Topolcany",
    "Lucenec",
    "Cadca",
    "Dubnica nad Vahom",
    "Rimavska Sobota",
    "Partizanske",
    "Sala",
    "Hlohovec",
    "Dunajska Streda",
    "Vranov nad Toplou",
    "Brezno",
    "Trebisov",
    "Nove Mesto nad Vahom",
    "Snina",
    "Senica",
    "Pezinok",
    "Banovce nad Bebravou",
    "Dolny Kubin",
    "Ziar nad Hronom",
    "Roznava",
    "Puchov",
    "Handlova",
    "Malacky",
    "Sered",
    "Kezmarok",
    "Kysucke Nove Mesto",
    "Galanta",
    "Stara Lubovna",
    "Zlate Moravce",
    "Detva",
    "Skalica",
    "Senec",
    "Levoca",
    "Velky Krtis",
    "Revuca",
    "Myjava",
    "Svidnik",
    "Nova Dubnica",
    "Sabinov",
    "Samorin",
    "Sturovo",
    "Bytca",
    "Holic",
    "Banska Stiavnica",
    "Kolarovo",
    "Stropkov",
    "Surany",
    "Stara Tura",
    "Filakovo",
    "Velke Kapusany",
    "Tvrdosin",
    "Moldava nad Bodvou",
    "Vrable",
    "Velky Meder",
    "Krompachy",
    "Modra",
    "Hrinova",
    "Liptovsky Hradok",
    "Tornala",
    "Hurbanovo",
    "Namestovo",
    "Stupava",
    "Sahy",
    "Kralovsky Chlmec",
    "Krupina",
    "Turzovka",
    "Secovce",
    "Hnusta",
    "Zeliezovce",
    "Nova Bana",
    "Trstena",
    "Svit",
    "Vrutky",
    "Turcianske Teplice",
    "Krasno nad Kysucou",
    "Medzilaborce",
    "Zarnovica",
    "Gelnica",
    "Sobrance",
    "Vrbove",
    "Nemsova",
    "Spisska Bela",
    "Lipany",
    "Poltar",
    "Sladkovicovo",
    "Rajec",
    "Kremnica",
    "Brezova pod Bradlom",
    "Ilava",
    "Vysoke Tatry",
    "Gbely",
    "Bojnice",
    "Sastin-Straze",
    "Dobsina",
    "Sliac",
    "Cierna nad Tisou",
    "Svaty Jur",
    "Strazske",
    "Trencianske Teplice",
    "Novaky",
    "Tlmace",
    "Tisovec",
    "Medzev",
    "Giraltovce",
    "Velky Saris",
    "Leopoldov",
    "Spisske Podhradie",
    "Hanusovce nad Toplou",
    "Spisske Vlachy",
    "Jelsava",
    "Podolinec",
    "Rajecke Teplice",
    "Spisska Stara Ves",
    "Dudince",
    "Modry Kamen"
}
